name: k4llyEnchant-MC1.9
version: 0.2.1-Beta
author: K4LLy
main: de.k4lly.enchant.Main
commands:
  kEVersion:
    description: Used to get the actual Version of this Plugin.
    usage: /kEVersion
  k4llyEnchant:
    description: Used to Set the max level of an enchantment.
    usage: /k4llyEnchant [set/s] <enchantment/ID> <max-level>
  kE:
    description: Used to Set the max level of an enchantment.
    usage: /k4llyEnchant [set/s] <enchantment/ID> <max-level>