name: k4llyEnchant-MC1.11
version: 0.3.2-Beta
author: K4LLy
main: de.k4lly.enchant.Main
commands:
  kEVersion:
    description: Used to get the actual Version of this Plugin.
    usage: /kEVersion
  k4llyEnchant:
    description: Used to change config.
    usage: /k4llyEnchant [set/s] <config> <value>
  kE:
    description: Used to change config.
    usage: /k4llyEnchant [set/s] <config> <value>