name: k4llyEnchant
version: 0.1.0-Beta
author: K4LLy
main: de.k4lly.enchant.Main
commands:
  k4llyEnchant:
    description: Used to Set the max level of an enchantment.
    usage: /k4llyEnchant [set/s] <enchantment/ID> <max-level>
  kE:
    description: Used to Set the max level of an enchantment.
    usage: /k4llyEnchant [set/s] <enchantment/ID> <max-level>