name: k4llyEnchant-MC1.11
version: 0.4.9-Beta
author: K4LLy
main: de.k4lly.enchant.Main
commands:
  kEVersion:
    description: Shows the actual Version of this Plugin.
    usage: /kEVersion
  k4llyEnchant:
    description: Used to change the config.
    usage: /k4llyEnchant [set/s] <config> <value>
  kE:
    description: Used to change the config.
    usage: /k4llyEnchant [set/s] <config> <value>